### PR TITLE
fix: Update bump-version.R - replace length test in get_main_branch_config()

### LINKED ISSUE #767: get_main_branch_config() reliance on length(tablename) fails with 0 row table
I just found this package and was very excited, unfortunately I haven't been able to get it to work yet. I've troubleshot a few of the stumbling blocks to getting `fledge::bump_version()` to work but this one seems to be impassable.

In [bump-version.R](https://github.com/cynkra/fledge/blob/7e2964fbe1080d234ed890bcaf7b3f6ecf107359/R/bump-version.R#L98) `get_main_branch_config()` (line 98) relies on the test `length(local)` (line 103). Dataframes, tibbles, and data.tables all return their number of columns for `length()`, even if they are empty. This causes `get_main_branch_config()` to spuriously return `init[init$level == "local", ]$value` (line 104) instead of ` init[init$level == "global"]$value` (line 108)

Below is a redacted sample of my exact data to demonstrate

```R

# object 'config' as would be retrieved by gert::git_config(repo)
config<-structure(list(name = c("diff.astextplain.textconv", "filter.lfs.clean", 
"filter.lfs.smudge", "filter.lfs.process", "filter.lfs.required", 
"http.sslbackend", "http.sslcainfo", "core.autocrlf", "core.fscache", 
"core.symlinks", "pull.rebase", "credential.helper", "credential.https://dev.azure.com.usehttppath", 
"core.editor", "core.excludesfile", "gui.recentrepo", "user.email", 
"user.name", "init.defaultbranch", "core.repositoryformatversion", 
"core.filemode", "core.bare", "core.logallrefupdates", "core.symlinks", 
"core.ignorecase", "remote.origin.url", "remote.origin.fetch", 
"branch.main.remote", "branch.main.merge"), value = c("astextplain", 
"git-lfs clean -- %f", "git-lfs smudge -- %f", "git-lfs filter-process", 
"true", "openssl", "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt", 
"true", "true", "false", "false", "manager-core", "true", "\"C:\\Users\\Foo\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe\" --wait", 
"C:/Users/Foo/.gitignore", "C:/foo/bar/baz/foobar", 
"foo@bar.baz", "Foo Bar", "main", "0", "false", 
"false", "true", "false", "true", "http://giteahere:3000/Foo/Bar.git", 
"+refs/heads/*:refs/remotes/origin/*", "origin", "refs/heads/main"
), level = c("system", "system", "system", "system", "system", 
"system", "system", "system", "system", "system", "system", "system", 
"system", "global", "global", "global", "global", "global", "global", 
"local", "local", "local", "local", "local", "local", "local", 
"local", "local", "local")), row.names = c(NA, 29L), class = c("tbl_df", 
"tbl", "data.frame"))

# contents of get_main_branch_config() configured to run interactively
init <- config[config$name == "init.defaultbranch", ]
print(init)

# A tibble: 1 × 3
#  name               value  level 
#  <chr>              <chr>  <chr> 
#1 init.defaultbranch main global

local <- init[init$level == "local", ] 
print(local)
# A tibble: 0 × 3
# ℹ 3 variables: name <chr>, value <chr>, level <chr>

if (length(local)) {  # this test fails because length(local)==3, _nrow(local)_==0
  print(local$value)    # the function prematurely ends, returning an empty table here
} else {
  global <- init[init$level == "global"] # this is missing a comma and would also break
  print(global$value)
}
```

If you want to stick with base R this is what I would suggest:

```R
  get_main_branch_config <- function(repo) {
  #retrieve config of repo, filter down to init.defaultbranch values
  config <- gert::git_config(repo)
  init <- config[config$name == "init.defaultbranch", ]

  #return local default branch if it exists, otherwise default to global
  if("local" %in% init$level){
    return(init[init$level == "local",]$value)
  } else { 
    return(init[init$level == "global",]$value)
  }
}
```

You could also just get rid of this function entirely.

```R
get_main_branch <- function(repo = getwd()) {
  remote <- "origin"            #hardcoded "origin" remote name 
  remote_list <- gert::git_remote_list(repo)
  if (remote %in% remote_list$name) {
    remote_main <- get_main_branch_remote(remote, repo)
    if (length(remote_main)) {
      return(remote_main)
    }
  } else{ 
    init<-gert::git_config(getwd())[config$name == "init.defaultbranch",]
    if("local" %in% init$level){
      return(init[init$level == "local",]$value)
    } else { 
      return(init[init$level == "global",]$value)
    }
  }
}
```

### PR DESCRIPTION
**Pull request by D3SL**
Closes #767 
length(table) always returns the number of columns, even for an empty (no rows) table. New test looks for the string "local" in init$level.

### CODE REVIEW

File: R/bump-version.R [hunk 1]
```diff
@@ -95,17 +95,17 @@ get_main_branch_remote <- function(remote, repo) {
   basename(as.character(remotes$symref[remotes$ref == "HEAD"]))
 }
 
-get_main_branch_config <- function(repo) {
+  get_main_branch_config <- function(repo) {
```
Comment (maelle) [inline R/bump-version.R:98]: why change the indentation level?

File: R/bump-version.R [hunk 2]
```diff
@@ -95,17 +95,17 @@ get_main_branch_remote <- function(remote, repo) {
...
+  #retrieve config of repo, filter down to init.defaultbranch values
   config <- gert::git_config(repo)
   init <- config[config$name == "init.defaultbranch", ]
-  local <- init[init$level == "local", ]
 
-  if (length(local)) {
-    return(local$value)
+  #return local default branch if it exists, otherwise default to global
```
Comment (maelle) [inline R/bump-version.R:103]: I think the comments can be removed as the code is clear enough: https://blog.r-hub.io/2023/01/26/code-comments-self-explaining-code/

**Review by maelle — CHANGES_REQUESTED** [review]
Thank you!!

Can you edit your first GitHub comment in the PR to make it refer to the issue it's closing? See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

File: R/bump-version.R (hunk 1 above)
Comment (D3SL) [reply R/bump-version.R]: I'm not sure, it wasn't intentional. Could be a whitespace character artefact or some hiccup with trying to paste code from my IDE into github's online editor. ~Is there a way to get rid of that without redoing the whole PR from scratch?~

edit: I think I did it.

File: R/bump-version.R (hunk 2 above)
Comment (D3SL) [reply R/bump-version.R:103]: I think you're right. What would be more helpful is a comment explaining the purpose behind this internal function. It's somewhat redundant at the moment but if you support more configurations in the future it will come in handy.

Comment (maelle) [reply R/bump-version.R:103]: thank you! Can you remove the comments then? An alternative to adding a comment about the function would be to improve its name.

Comment (D3SL) [reply R/bump-version.R]: Okay I think I got it right this time. Github is almost as complicated as git itself.

Comment (maelle) [reply R/bump-version.R]: For sure, there's quite the learning curve. Some resources although you didn't ask :innocent: 

- https://happygitwithr.com/
- https://usethis.r-lib.org/articles/pr-functions.html
- https://masalmon.eu/tags/git/

**Comment by maelle** [comment]
Thanks a lot @D3SL!!
